---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: sample-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
